[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.migrate]
cmds = [
  "echo 'ğŸš€ Running Drizzle migrations...'",
  "npx drizzle-kit migrate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"